version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apache-php
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=app_db
      - DB_CHARSET=utf8
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - TOKEN_SECRET=some secret
      - TOKEN_ISSUER=MyCompany
      - LOGIN_TOKEN_VALIDATION_IN_SECONDS=789000
      - REFRESH_TOKEN_VALIDATION_IN_SECONDS=43200
      - ACCESS_TOKEN_VALIDATION_IN_SECONDS=1200
      - QUERY_LIMIT=10
      - SERVICE_IN_URL_SECTION=1
      - METHOD_IN_URL_SECTION=2
    depends_on:
      db:
        condition: service_healthy
    networks:
      - gemvc-network

  db:
    image: mysql:8.0
    container_name: mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --authentication-policy=caching_sha2_password
      - --host-cache-size=0
      - --pid-file=/var/lib/mysql/mysql.pid
      - --disable-ssl
      - --log-error-verbosity=1
      - --skip-log-bin
      - --skip-name-resolve
      - --skip-symbolic-links
      - --innodb-flush-log-at-trx-commit=2
      - --innodb-buffer-pool-size=128M
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gemvc-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - gemvc-network

networks:
  gemvc-network:
    driver: bridge

volumes:
  db_data:
