version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
    volumes:
      - .:/var/www/html
    depends_on:
      - redis
      - mysql
    networks:
      - gemvc-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - gemvc-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gemvc
      MYSQL_USER: gemvc
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gemvc-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - gemvc-network

volumes:
  mysql_data:

networks:
  gemvc-network:
    driver: bridge

