version: '3.8'

services:
  app:
    build: .
    ports:
      - "9501:9501"
    environment:
      - APP_ENV=production
    volumes:
      - .:/var/www/html
    depends_on:
      - redis
      - mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gemvc
      MYSQL_USER: gemvc
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
